### PR TITLE
add missing blank lines

### PR DESCRIPTION
**Pull request by mikaelarguedas**
fixes the flake8 failures on the [last nightlies](http://ci.ros2.org/view/nightly/job/nightly_linux_release/lastCompletedBuild/testReport/)

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
seems to be linked to https://gitlab.com/pycqa/flake8/issues/256
Need more investigation to confirm that this change is necessary

**Comment by wjwwood** [comment]
Yeah, I agree we need to look at this closer, because as I understand it, it should not be necessary to have two blanks lines before code that is not a class or function definition.

**Comment by Karsten1987** [comment]
Can this be merged?!

**Comment by mikaelarguedas** [comment]
I didn't have time to look if the new flake8/pydocstyle rule is a regression of the linter or a new stricter rule of the standard.
In the meantime we could merge this and revert it if it proves to be a regression that ends up being fixed upstream. But that requires ticketing it and monitoring the upstream repos.

**Comment by wjwwood** [comment]
This change looks intentional, though I don't really like it:

https://github.com/PyCQA/pycodestyle/issues/400
https://github.com/PyCQA/pycodestyle/pull/402

I'll just merge this and we'll just go along for now to fix the CI. Perhaps in the future we can consider disabling E305 (which is a new error for this case) so we can keep the current style.

**Comment by wjwwood** [comment]
Thanks @mikaelarguedas for taking the initiative to fix it in the first place 😄. I'm actually surprised this error hasn't come up in other places yet.

**Comment by mikaelarguedas** [comment]
sounds good to me, thanks for looking into it

**Pull request merged**
