### PR TITLE
Fix osrf.py_common.process_utils.get_loop() implementation

### PR DESCRIPTION
**Pull request by hidmic**
On Windows, avoid loops closing during garbage collection and reuse existing ones if possible.

Connected to https://github.com/ros2/launch/pull/476.

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Review by clalancette — COMMENTED** [review]
From a naive view, it looks like this shouldn't be necessary; the first time we come in here, the TLS `loop_has_been_setup` will be False, we'll unconditionally create the `ProactorEventLoop`, and then set `loop_has_been_setup` to True.  Subsequent invocations should always just use the earlier `get_event_loop`.  Could you explain a bit more why this is needed?

**Comment by hidmic** [comment]
CI up to `launch`, `test_launch_ros`, `test_communication`, and `osrf_pycommon`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13409/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8329/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11134/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13468/)

**Comment by hidmic** [comment]
> From a naive view, it looks like this shouldn't be necessary; the first time we come in here, the TLS loop_has_been_setup will be False, we'll unconditionally create the ProactorEventLoop, and then set loop_has_been_setup to True. Subsequent invocations should always just use the earlier get_event_loop. Could you explain a bit more why this is needed?

Thing is, the event loop for the current thread may have already been set (e.g. through regular `asyncio` API). On Unix, we simply use the one set. But on Windows, we were always overriding it. If my analysis is correct (and I believe so, because I don't get hangs anymore), this creates a fun scenario if the event loop that was previously set was an `asyncio.ProactorEventLoop` itself. Once we override it, if there are no references to it, it'll eventually be garbage collected. When it is garbage collected, and Python's garbage collector runs in the main thread, that loop gets closed, and _boom_! [Signal wakeups are disabled](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Lib/asyncio/proactor_events.py#L680-L681), affecting the other `asyncio.ProactorEventLoop` instance that is running.

**Comment by ivanpauno** [comment]
> When it is garbage collected, and Python's garbage collector runs in the main thread, that loop gets closed, and boom! Signal wakeups are disabled, affecting the other asyncio.ProactorEventLoop instance that is running.

omg, wonderful finding :sweat_smile:

**Review by ivanpauno — APPROVED** [review]

**Comment by clalancette** [comment]
> Thing is, the event loop for the current thread may have already been set (e.g. through regular `asyncio` API). On Unix, we simply use the one set. But on Windows, we were always overriding it. If my analysis is correct (and I believe so, because I don't get hangs anymore), this creates a fun scenario if the event loop that was previously set was an `asyncio.ProactorEventLoop` itself. Once we override it, if there are no references to it, it'll eventually be garbage collected. When it is garbage collected, and Python's garbage collector runs in the main thread, that loop gets closed, and _boom_! [Signal wakeups are disabled](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Lib/asyncio/proactor_events.py#L680-L681), affecting the other `asyncio.ProactorEventLoop` instance that is running.

Wow, deep stuff.  Good find.  So am I right in thinking that the main fix here is the close of the old loop and the open of a new `ProactorEventLoop` under Windows?  If so, it might be worthwhile to put a comment explaining that, just because it is non-obvious from the context.

**Comment by wjwwood** [comment]
I didn't know the context for the issue. I just assumed the closing in the gc might be an issue if it is actually a singleton but didn't ask  after it. Nice to hear the explanation. I agree a comment detailing why this code is like this would be useful.

**Review by clalancette — APPROVED** [review]

**Review by wjwwood — APPROVED** [review]

**Comment by hidmic** [comment]
FYI https://bugs.python.org/issue42913.

**Pull request merged**
