### PR TITLE
[backport foxy] Fix osrf.py_common.process_utils.get_loop() implementation (#70)

### PR DESCRIPTION
**Pull request by hidmic**
On Windows, avoid loops closing during garbage collection and reuse existing ones if possible.

Signed-off-by: Michel Hidalgo <michel@ekumenlabs.com>

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
I'll wait on feedback from @jacobperron and CI to merge.

**Review by jacobperron — APPROVED** [review]
LGTM. I haven't reviewed the launch PR yet.

**Comment by hidmic** [comment]
Full Foxy CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14788/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9537/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12454/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14935/)

**Comment by wjwwood** [comment]
I think the failures in CI are unrelated to this, but it would be good to get a 👍 from either of you @hidmic @jacobperron, before I merge.

Also, @hidmic should this target the `foxy` branch instead of `master`?

**Comment by jacobperron** [comment]
Yeah, I think this should target the `foxy` branch. 

All of the CI failures appear like pre-existing issues, except this one looks new (maybe coming from the connected PR?): https://ci.ros2.org/job/ci_windows/14935/testReport/junit/launch.test.launch.utilities/test_signal_management/test_on_sigquit/

**Comment by hidmic** [comment]
> Also, @hidmic should this target the foxy branch instead of master?

Yes... :facepalm: PR rebased.

**Comment by hidmic** [comment]
> All of the CI failures appear like pre-existing issues, except this one looks new (maybe coming from the connected PR?): https://ci.ros2.org/job/ci_windows/14935/testReport/junit/launch.test.launch.utilities/test_signal_management/test_on_sigquit/

There's no SIGQUIT on Windows. https://github.com/ros2/launch/pull/511/commits/4b7e29b5616ad990943340ddda88546e64fb3a0d will do the trick.

**Comment by hidmic** [comment]
Full Foxy CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14794/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9543/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12460/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14941/)

**Review by wjwwood — APPROVED** [review]

**Comment by hidmic** [comment]
Warnings on Windows and MacOS are unrelated. Merging!

**Pull request merged**
